---
# tasks file for Slave

- name: Installing docker
  package:
    name: docker
    state: present
    
- name: starting docker services
  service:
    name: "docker"
    state: started
    enabled: yes
    
- name: configuring yum for kubeadm
  yum_repository:
    name: "kubernetes"
    description: "repo for kubernetes"
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    repo_gpgcheck: yes
    gpgcheck: yes
    gpgkey: 
    -  "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
    -  "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    
- name: Installing kubeadm, kubectl and kubelet
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: "kubernetes"

- name: starting and enabling kubelet services
  service:
    name: "kubelet"
    state: started
    enabled: yes
        
- name: Pulling Images using kubeadm
  shell: "kubeadm config  images pull"
  changed_when: false
     
- name: Installing iproute-tc
  package:
     name: iproute-tc
     
- name: copy daemon file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Restarting Docker
  service:
    name: docker
    state:  restarted

- name: Updating k8s config file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    src: k8s.conf
    
- name: restarting sysctl
  command: sysctl --system
  
- name: Send Master Token to Slave
  copy:
          src: "/task19/token"
          dest: "/tmp/token"

- name: Join the Kubernetes Cluster
  shell: "bash /tmp/token"
  ignore_errors: True
